name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21 (JetBrains)
      uses: actions/setup-java@v5
      with:
        distribution: 'jetbrains'
        java-version: '21'
        java-package: 'jdk'

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Set Gradle toolchain path
      run: echo "GRADLE_OPTS=-Dorg.gradle.java.installations.paths=$JAVA_HOME" >> $GITHUB_ENV

    - name: Show JAVA_HOME for debug
      run: |
        echo "JAVA_HOME=$JAVA_HOME"
        $JAVA_HOME/bin/java -version

    - name: Run Ktlint
      run: ./gradlew ktlintCheck
      continue-on-error: true

    - name: Run Detekt
      run: ./gradlew detekt
      continue-on-error: true

    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest
